-- Create components table
CREATE TABLE IF NOT EXISTS components (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  type TEXT NOT NULL,
  price DECIMAL(15, 2) NOT NULL,
  image_url TEXT,
  specs TEXT,
  description TEXT,
  marketplace_link TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Create monitors table
CREATE TABLE IF NOT EXISTS monitors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  resolution TEXT,
  refresh_rate INTEGER,
  panel_type TEXT,
  screen_size DECIMAL(5, 2),
  price DECIMAL(15, 2) NOT NULL,
  rating DECIMAL(3, 2) DEFAULT 0,
  featured BOOLEAN DEFAULT FALSE,
  image_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE components ENABLE ROW LEVEL SECURITY;
ALTER TABLE monitors ENABLE ROW LEVEL SECURITY;

-- Create policies to allow public read access
CREATE POLICY "Public components are viewable by everyone" ON components
  FOR SELECT USING (true);

CREATE POLICY "Public monitors are viewable by everyone" ON monitors
  FOR SELECT USING (true);

-- Create policies to allow authenticated users to insert/update/delete (adjust as needed for Admin only)
CREATE POLICY "Enable insert for authenticated users only" ON components
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Enable update for authenticated users only" ON components
  FOR UPDATE USING (auth.role() = 'authenticated');

CREATE POLICY "Enable delete for authenticated users only" ON components
  FOR DELETE USING (auth.role() = 'authenticated');

CREATE POLICY "Enable insert for authenticated users only" ON monitors
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Enable update for authenticated users only" ON monitors
  FOR UPDATE USING (auth.role() = 'authenticated');

CREATE POLICY "Enable delete for authenticated users only" ON monitors
  FOR DELETE USING (auth.role() = 'authenticated');
